name: connpass-feed
on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 0 * * *'

jobs:
  connpass-feed:
    name: "create feed"
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0'
      - name: install
        run: |
          gem install connpass -v 0.0.1
          gem install rexml -v 3.2.5
      - name: generate feed
        run: ruby gen.rb
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
